### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by bpandola** [hsdp/python-cf-api#1]
Trying to install the package results in the following error:

```
$ pip install cf-api
Collecting cf-api
  Downloading cf_api-0.1.9.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 1.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cv/tpxj6vdx65v4dztfcmwcvhyw0000gn/T/pip-build-vSsW31/cf-api/setup.py", line 15, in <module>
        license=open('LICENSE').read(),
    IOError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cv/tpxj6vdx65v4dztfcmwcvhyw0000gn/T/pip-build-vSsW31/cf-api/
```

I would suggest including `LICENSE` in your `MANIFEST.in` file and simple putting the name of the license (`Apache Software License 2.0`) in your package metadata.

**Comment by adamjaso** [comment]
Ok. I've updated `MANIFEST.in`. `v0.1.10` should fix the problem.
